# Generated by Django 4.0.3 on 2022-03-19 16:57

import uuid

import django.db.models.deletion
from django.db import migrations, models

import payments.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("amount", models.FloatField()),
                (
                    "made_through",
                    models.CharField(
                        default=payments.constants.PaymentProviders, max_length=255
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("state", models.CharField(default="PENDIGN", max_length=255)),
                ("verified", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="partner.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
