# Generated by Django 4.0.1 on 2022-02-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("made_at", models.DateTimeField(auto_now=True, null=True)),
                ("amount", models.IntegerField()),
                ("transaction_id", models.CharField(max_length=256)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partner.person",
                    ),
                ),
            ],
        ),
    ]
