# Generated by Django 4.0.2 on 2022-02-19 13:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("made_at", models.DateTimeField(auto_now=True, null=True)),
                ("amount", models.IntegerField()),
                ("transaction_id", models.CharField(max_length=256)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="partner.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
