# Generated by Django 4.0.2 on 2022-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="made_through",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="state",
            field=models.CharField(default="PENDIGN", max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
