# Generated by Django 4.0.2 on 2022-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_made_through_payment_state_payment_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="made_at",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.FloatField(),
        ),
    ]
