# Generated by Django 4.0.2 on 2022-03-06 15:39

from django.db import migrations, models

import payments.constants


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="made_through",
            field=models.CharField(
                default=payments.constants.PaymentProviders.MPESA.value, max_length=255
            ),
        ),
    ]
