# Generated by Django 4.1.1 on 2022-09-24 21:50

from typing import Any, Type, cast

from django.db import migrations, models


def corrent_pending_typo(apps: Any, schema_editor: Any) -> None:
    from payments.models import Payment

    Payment_: Type[Payment] = apps.get_model("payments", "Payment")

    for payment in Payment_.objects.filter(**{"state": "PENDIGN"}):
        payment = cast(Payment, payment)
        payment.state = "PENDING"
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="state",
            field=models.CharField(default="PENDING", max_length=255),
        ),
        migrations.RunPython(corrent_pending_typo),
    ]
