# Generated by Django 4.1.2 on 2022-11-11 21:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("MPESA", "MPESA"), ("BANK", "BANK")],
                        default="MPESA",
                        max_length=255,
                    ),
                ),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
