# Generated by Django 4.0.2 on 2022-03-08 20:53

from django.db import migrations, models

import payments.constants


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_made_through"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="made_through",
            field=models.CharField(
                default=payments.constants.PaymentProviders, max_length=255
            ),
        ),
    ]
