# Generated by Django 4.1.2 on 2022-11-27 20:24

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_payment_number_alter_paymentmethod_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.CharField(
                default=core.utils.generate_payment_number, max_length=255, unique=True
            ),
        ),
    ]
