# Generated by Django 4.1.2 on 2023-02-23 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0011_alter_partner_bank_account_number_and_more"),
        ("payments", "0008_alter_payment_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BTransactionLogs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("state", models.CharField(default="FAILED", max_length=255)),
                ("message", models.CharField(max_length=2048)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="partner.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
