# Generated by Django 4.0.2 on 2022-02-19 13:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(default="new-event", max_length=256)),
                ("poster", models.ImageField(upload_to="media/")),
                ("event_date", models.DateField()),
                ("event_location", models.CharField(max_length=1024)),
                ("description", models.CharField(max_length=1024)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Has the event been published"
                    ),
                ),
                (
                    "event_state",
                    models.CharField(
                        choices=[
                            ("PR", "PRE_REVIEW"),
                            ("AE", "ACTIVE"),
                            ("PC", "PRE_CLOSED"),
                            ("CD", "CLOSED"),
                        ],
                        default="PR",
                        max_length=256,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("price", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "amsg",
                    models.CharField(
                        default="Open Soon",
                        max_length=256,
                        verbose_name="Active Message",
                    ),
                ),
                ("amount", models.IntegerField(default=100)),
                (
                    "is_visible",
                    models.BooleanField(
                        default=False, verbose_name="Is Ticket Visible To Users"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("promotion_rate", models.IntegerField(default=100)),
                ("expiry", models.DateField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.tickettype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("promotion_rate", models.IntegerField(default=100)),
                ("expiry", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
