# Generated by Django 4.0.1 on 2022-02-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="new-event", max_length=256, null=True
                    ),
                ),
                ("poster", models.ImageField(upload_to="media/")),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "event_location",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("description", models.CharField(max_length=1024)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Has the event been published"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("price", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "amsg",
                    models.CharField(
                        default="Open Soon",
                        max_length=256,
                        verbose_name="Active Message",
                    ),
                ),
                ("amount", models.IntegerField(default=100)),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Is Ticket Visible To Users"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("promotion_rate", models.IntegerField(default=100)),
                ("expiry", models.DateField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.tickettype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("promotion_rate", models.IntegerField(default=100)),
                ("expiry", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
