# Generated by Django 4.0.2 on 2022-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpromotion",
            name="use_limit",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="ticketpromotion",
            name="use_limit",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_state",
            field=models.CharField(
                choices=[
                    ("PR", "PRE_REVIEW"),
                    ("AE", "ACTIVE"),
                    ("PC", "PRE_CLOSED"),
                    ("CD", "CLOSED"),
                    ("AD", "ARCHIVED"),
                ],
                default="PR",
                max_length=256,
            ),
        ),
    ]
