# Generated by Django 4.0.4 on 2022-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_ticket_uses_tickettype_use_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="hash",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
