# Generated by Django 4.0.2 on 2022-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventpromotion_use_limit_ticketpromotion_use_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpromotion",
            name="promotion_rate",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="ticketpromotion",
            name="promotion_rate",
            field=models.IntegerField(default=10),
        ),
    ]
