# Generated by Django 4.0.4 on 2022-05-14 11:55

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_ticket_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_number",
            field=models.CharField(
                default=core.utils.generate_event_number, max_length=255
            ),
        ),
    ]
