# Generated by Django 4.0.2 on 2022-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_eventpromotion_promotion_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpromotion",
            name="promotion_rate",
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name="ticketpromotion",
            name="promotion_rate",
            field=models.FloatField(default=10.0),
        ),
    ]
