# Generated by Django 4.1 on 2022-08-21 23:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0008_alter_partner_created_at_and_more"),
        ("events", "0006_ticket_ticket_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="event_end_date",
            field=models.DateField(default="2222-12-31"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PartnerPersonSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "partner_person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partnerperson",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
