# Generated by Django 4.0.1 on 2022-03-09 18:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payment_made_through"),
        ("events", "0006_eventcategory_alter_event_time_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(default="21:24"),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "sent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Has the ticket been sent to the user",
                    ),
                ),
                (
                    "redeemed",
                    models.BooleanField(
                        default=False, verbose_name="Has the ticket been redeemed"
                    ),
                ),
                ("hash", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payment",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.tickettype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
