# Generated by Django 4.1 on 2022-08-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0009_partnerperson_person_number_and_more"),
        ("events", "0007_event_end_time_event_event_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="_assigned_ticketing_agents",
            field=models.ManyToManyField(
                through="events.PartnerPersonSchedule", to="partner.partnerperson"
            ),
        ),
    ]
