# Generated by Django 4.0.1 on 2022-03-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_time_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(default="22:10"),
        ),
    ]
