# Generated by Django 4.1.1 on 2022-09-28 23:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0009_partnerperson_person_number_and_more"),
        ("events", "0008_event__assigned_ticketing_agents"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partnerperson",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.ticket"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
