# Generated by Django 4.1.2 on 2022-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_ticketscan_redeem_triggered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpromotion",
            name="promotion_rate",
            field=models.FloatField(default=1.0),
        ),
    ]
