# Generated by Django 4.0.3 on 2022-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_time_reminderoptin_promooptin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(default="15:40"),
        ),
    ]
