# Generated by Django 4.1.7 on 2023-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_eventpromotion_promotion_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=True, verbose_name="Is the event publically listed"
            ),
        ),
    ]
