repos:
  - repo: local
    hooks:
      - id:  sync-requirements
        name: sync-requirements
        entry: ./scripts/pre-commit.sh
        language: script
        types: [python]
        pass_filenames: false
        always_run: true