# Generated by Django 4.1.7 on 2023-03-10 14:48

import uuid

import django.db.models.deletion
from django.db import migrations, models

import partner_api.models
import partner_api.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner", "0011_alter_partner_bank_account_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCredentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "secret",
                    models.CharField(
                        default=partner_api.utils.generate_resource_secret,
                        max_length=255,
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiAuthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "expiry",
                    models.DateTimeField(
                        default=partner_api.models.default_token_expiry
                    ),
                ),
                (
                    "refresh_expiry",
                    models.DateTimeField(
                        default=partner_api.models.default_refresh_token_expiry
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
