# Generated by Django 4.1.7 on 2023-03-16 16:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_eventpromotion_promotion_rate"),
        ("partner", "0011_alter_partner_bank_account_number_and_more"),
        ("partner_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("amount", models.FloatField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partner.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentIntentTicketType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner_api.paymentintent",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.tickettype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="ticket_type_rel",
            field=models.ManyToManyField(
                through="partner_api.PaymentIntentTicketType", to="events.tickettype"
            ),
        ),
    ]
