# Generated by Django 4.1.7 on 2023-03-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_api", "0002_paymentintent_paymentintenttickettype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="redirect_to",
            field=models.URLField(default="http://localhost:8000/payments"),
            preserve_default=False,
        ),
    ]
