# Generated by Django 4.1.7 on 2023-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_api", "0004_rename_redirect_to_paymentintent_callback_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintenttickettype",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
