# Generated by Django 4.0.1 on 2022-02-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('events', '0002_event_partner'),
        ('payments', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.person'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='redeemed',
            field=models.BooleanField(default=False, verbose_name='Has the ticket been redeemed'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Has the ticket been sent to the user'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tickettype'),
            preserve_default=False,
        ),
    ]
