# Generated by Django 4.0.2 on 2022-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
