# Generated by Django 4.0.2 on 2022-02-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_payment_ticket_person_ticket_redeemed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="person",
        ),
    ]
