# Generated by Django 4.0.1 on 2022-03-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_hash"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
