# Generated by Django 4.0.3 on 2022-03-12 19:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner", "0007_partner_comission_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("message", models.CharField(max_length=2048)),
                ("channel", models.CharField(default="EMAIL", max_length=255)),
                ("has_data", models.BooleanField(default=True)),
                ("sent", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partner.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MassNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("channel", models.CharField(default="EMAIL", max_length=255)),
                ("has_data", models.BooleanField(default=True)),
                ("sent", models.BooleanField(default=False)),
                ("people", models.ManyToManyField(to="partner.person")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
