# Generated by Django 4.0.3 on 2022-03-19 16:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("comission_rate", models.FloatField(default=3.0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerBankingInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("bank_code", models.IntegerField()),
                ("bank_account_number", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "email",
                    models.CharField(
                        default="0", max_length=256, verbose_name="E-mail"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("hashed_password", models.CharField(max_length=1024)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromoOptIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partner.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerSMS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "per_sms_rate",
                    models.FloatField(default=0.0, verbose_name="Partner Cost Per SMS"),
                ),
                ("sms_limit", models.IntegerField(default=0)),
                ("sms_used", models.IntegerField(default=0)),
                ("verified", models.BooleanField(default=False)),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=1024)),
                (
                    "repeat",
                    models.CharField(
                        choices=[("WK", "WEEKLY"), ("MN", "MONTHLY"), ("FX", "FIXED")],
                        default="MN",
                        max_length=255,
                    ),
                ),
                ("message", models.TextField(max_length=10240)),
                ("start_on", models.DateField(auto_now_add=True)),
                ("last_run", models.DateField(auto_now_add=True)),
                ("stops_on", models.DateField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("PM", "PARTNER_MEMBER"),
                            ("TA", "TICKETING_AGENT"),
                            ("CR", "CUSTOMER"),
                            ("OW", "OWNER"),
                        ],
                        default="CR",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is the member active"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, verbose_name="Is the person hidden"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="partner.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="banking_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="partner.partnerbankinginfo",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partner.person",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="partner.person",
            ),
        ),
    ]
