# Generated by Django 4.0.2 on 2022-02-27 09:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="person_type",
        ),
        migrations.CreateModel(
            name="PartnerPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("PR", "PARTNER"),
                            ("TA", "TICKETING_AGENT"),
                            ("CR", "CUSTOMER"),
                        ],
                        default="CR",
                        max_length=255,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partner.partner",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partner.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
