# Generated by Django 4.0.3 on 2022-03-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partnerpromotion",
            old_name="start_on",
            new_name="starts_on",
        ),
    ]
