# Generated by Django 4.0.2 on 2022-02-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0002_remove_person_person_type_partnerperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="partner.person",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="partnerperson",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="partner.person",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="partnerperson",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("PM", "PARTNER_MEMBER"),
                    ("TA", "TICKETING_AGENT"),
                    ("CR", "CUSTOMER"),
                    ("OW", "OWNER"),
                ],
                default="CR",
                max_length=255,
            ),
        ),
    ]
