# Generated by Django 4.0.3 on 2022-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0002_rename_start_on_partnerpromotion_starts_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpromotion",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="partnerpromotion",
            name="repeat",
            field=models.CharField(
                choices=[("WK", "WEEKLY"), ("MN", "MONTHLY"), ("FX", "FIXED")],
                default="FX",
                max_length=255,
            ),
        ),
    ]
