# Generated by Django 4.0.3 on 2022-03-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0003_partnerpromotion_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="banking_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="partner.partnerbankinginfo",
            ),
        ),
    ]
