# Generated by Django 4.0.2 on 2022-02-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0003_alter_partner_owner_alter_partnerperson_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="partner.person",
            ),
        ),
        migrations.AlterField(
            model_name="partnerperson",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="partner.person"
            ),
        ),
    ]
