# Generated by Django 4.0.2 on 2022-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0004_alter_partner_owner_alter_partnerperson_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerperson",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Is the member active"
            ),
        ),
        migrations.AddField(
            model_name="partnerperson",
            name="is_hidden",
            field=models.BooleanField(
                default=False, verbose_name="Is the person hidden"
            ),
        ),
    ]
