# Generated by Django 4.0.2 on 2022-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0005_partnerperson_is_active_partnerperson_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
