# Generated by Django 4.0.4 on 2022-05-10 11:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_alter_partnerperson_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempOTPStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("otp", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="partnersms",
            name="partner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_package",
                to="partner.partner",
            ),
        ),
    ]
