# Generated by Django 4.0.3 on 2022-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_alter_person_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="comission_rate",
            field=models.FloatField(default=3.0),
        ),
    ]
