# Generated by Django 4.0.4 on 2022-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0007_tempotpstore_alter_partnersms_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="partnerperson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="partnerpromotion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="partnersms",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="promooptin",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tempotpstore",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
