# Generated by Django 4.1 on 2022-08-30 21:36

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0008_alter_partner_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerperson",
            name="person_number",
            field=models.CharField(
                default=core.utils.generate_agent_number, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="partnerperson",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("PM", "PARTNER_MEMBER"),
                    ("TA", "TICKETING_AGENT"),
                    ("CR", "CUSTOMER"),
                    ("OW", "OWNER"),
                ],
                default="TA",
                max_length=255,
            ),
        ),
    ]
