# Generated by Django 4.1.2 on 2022-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0009_partnerperson_person_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerpromotion",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("WEEKLY", "WEEKLY"),
                    ("MONTHLY", "MONTHLY"),
                    ("SINGLE_RUN", "SINGLE_RUN"),
                ],
                default="SINGLE_RUN",
                max_length=255,
            ),
        ),
    ]
