# Generated by Django 4.1.2 on 2023-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0010_alter_partnerpromotion_repeat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="bank_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="partnersms",
            name="per_sms_rate",
            field=models.FloatField(
                default=0.0, verbose_name="Partner Cost Per SMS (KES)"
            ),
        ),
    ]
