# Generated by Django 4.1.7 on 2023-03-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0011_alter_partner_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
