name: PR Checks
on: 
  pull_request:
    branches:
      - master
concurrency:
  cancel-in-progress: true


jobs:
  Typing & Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files-app
        uses: tj-actions/changed-files@v7
        with:
          files: |
            .
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.12

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Run linting
        if: steps.changed-files-app.outputs.any_changed == 'true'
        run: |
          chmod +x scripts/lint.sh
          poetry run ./scripts/lint.sh