name: Deploy
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.head_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ticketzone-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}